apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infra/access
  - ../../../infra/kyverno
  - ../../../infra/longhorn
  - ../../../infra/metrics-server
  - ../../../infra/pod-report
  - ../../../infra/cloudflared
  - ../../../infra/wireguard
  - ../../../infra/backups
  - ../../../infra/observability
  - ../../../infra/priorityclasses
  - ../../../infra/namespaces/wotlk.yaml
  - ../../../infra/namespaces/wireguard.yaml
  - ../../../secrets/longhorn-b2-credentials.enc.yaml
  - ../../../secrets/restic-b2-photos.enc.yaml
  - ../../../secrets/gatus-github-token.enc.yaml
  - ../../../secrets/wotlk-mariadb-auth.enc.yaml
