apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyverno-github-issue-sync
  namespace: kyverno
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-github-issue-sync
rules:
  - apiGroups:
      - wgpolicyk8s.io
    resources:
      - clusterpolicyreports
      - policyreports
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kyverno.io
    resources:
      - policyexceptions
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-github-issue-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno-github-issue-sync
subjects:
  - kind: ServiceAccount
    name: kyverno-github-issue-sync
    namespace: kyverno