apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      enableServiceLinks: true
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:v1.13.2@sha256:a0b71c8e757298d02560186bab9fbe3fc2d375c523a62cc1019177b37e48aa28
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          startupProbe:
            httpGet:
              path: /api/healthcheck
              port: http
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /api/healthcheck
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /api/healthcheck
              port: http
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: TZ
              value: Australia/Melbourne
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "$(MY_POD_IP):3000,homepage.cooked.beer,192.168.1.190:30300,homepage.homepage.svc.cluster.local,homepage.homepage.svc.cluster.local:3000"
          volumeMounts:
            - name: app-config
              mountPath: /app/config/settings.yaml
              subPath: settings.yaml
            - name: app-config
              mountPath: /app/config/services.yaml
              subPath: services.yaml
            - name: app-config
              mountPath: /app/config/bookmarks.yaml
              subPath: bookmarks.yaml
            - name: app-config
              mountPath: /app/config/widgets.yaml
              subPath: widgets.yaml
            - name: app-config
              mountPath: /app/config/kubernetes.yaml
              subPath: kubernetes.yaml
            - name: app-config
              mountPath: /app/config/docker.yaml
              subPath: docker.yaml
            - name: app-config
              mountPath: /app/config/proxmox.yaml
              subPath: proxmox.yaml
            - name: app-config
              mountPath: /app/config/custom.css
              subPath: custom.css
            - name: app-config
              mountPath: /app/config/custom.js
              subPath: custom.js
            - name: logs
              mountPath: /app/config/logs
            - name: public-icons
              mountPath: /app/public/icons
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
      volumes:
        - name: logs
          emptyDir: {}
        - name: app-config
          configMap:
            name: homepage-app-config
        - name: public-icons
          configMap:
            name: homepage-public-icons
