apiVersion: batch/v1
kind: CronJob
metadata:
  name: wow-db-sync
  namespace: wow
spec:
  # Suspended by default; run manually when ready:
  # kubectl -n wow create job --from=cronjob/wow-db-sync wow-db-sync-1
  suspend: true
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: work
              emptyDir: {}
          initContainers:
            - name: clone
              image: alpine/git:2.47.2
              env:
                - name: WOW_DB_REPO
                  value: https://github.com/RovxBot/1.12.1-database.git
                - name: WOW_DB_REF
                  value: main
              command:
                - sh
                - -lc
                - |
                  set -euo pipefail
                  rm -rf /work/repo
                  git clone --depth=1 --branch "${WOW_DB_REF}" "${WOW_DB_REPO}" /work/repo
              volumeMounts:
                - name: work
                  mountPath: /work
          containers:
            - name: mariadb-client
              image: mariadb:11.4
              env:
                - name: DB_HOST
                  value: wow-mariadb.wow.svc.cluster.local
                - name: DB_PORT
                  value: "3306"
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: wow-mariadb-auth
                      key: MARIADB_DATABASE
                - name: DB_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: wow-mariadb-auth
                      key: MARIADB_ROOT_PASSWORD
                # Repo layout defaults (adjust to match your content repo):
                - name: WOW_DB_BOOTSTRAP_DIR
                  value: /work/repo/bootstrap
                - name: WOW_DB_MIGRATIONS_DIR
                  value: /work/repo/migrations
              command:
                - sh
                - -lc
                - |
                  set -euo pipefail

                  mysql() {
                    command mysql \
                      --protocol=tcp \
                      --host "${DB_HOST}" \
                      --port "${DB_PORT}" \
                      --user root \
                      --password="${DB_ROOT_PASSWORD}" \
                      "$@"
                  }

                  echo "Waiting for MariaDB at ${DB_HOST}:${DB_PORT}..."
                  for _ in $(seq 1 120); do
                    if mysql --execute "SELECT 1" >/dev/null 2>&1; then
                      break
                    fi
                    sleep 2
                  done

                  mysql --execute "CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\`;"

                  # Detect an empty database (no tables) and only then bootstrap.
                  table_count="$(mysql --database "${DB_NAME}" --skip-column-names --batch --execute \"SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='${DB_NAME}';\")"
                  if [ \"${table_count}\" -eq 0 ]; then
                    if [ -d \"${WOW_DB_BOOTSTRAP_DIR}\" ]; then
                      echo \"Bootstrapping DB from ${WOW_DB_BOOTSTRAP_DIR}...\"
                      find \"${WOW_DB_BOOTSTRAP_DIR}\" -maxdepth 1 -type f -name '*.sql' -print | sort | while read -r f; do
                        echo \"Applying bootstrap: ${f##*/}\"
                        mysql --database \"${DB_NAME}\" < \"$f\"
                      done
                    else
                      echo \"DB is empty, but no bootstrap dir found at ${WOW_DB_BOOTSTRAP_DIR}; skipping bootstrap.\"
                    fi
                  else
                    echo \"DB already initialized (${table_count} tables); skipping bootstrap.\"
                  fi

                  if [ -d \"${WOW_DB_MIGRATIONS_DIR}\" ]; then
                    echo \"Applying migrations from ${WOW_DB_MIGRATIONS_DIR}...\"
                    find \"${WOW_DB_MIGRATIONS_DIR}\" -maxdepth 1 -type f -name '*.sql' -print | sort | while read -r f; do
                      echo \"Applying migration: ${f##*/}\"
                      mysql --database \"${DB_NAME}\" < \"$f\"
                    done
                  else
                    echo \"No migrations dir found at ${WOW_DB_MIGRATIONS_DIR}; nothing to do.\"
                  fi
              volumeMounts:
                - name: work
                  mountPath: /work

