apiVersion: v1
kind: Service
metadata:
  name: wow-mangosd
  namespace: wow
spec:
  type: ClusterIP
  selector:
    app: wow-mangosd
  ports:
    - name: world
      port: 8085
      targetPort: world
      protocol: TCP
