apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media
  namespace: media
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: ""
  volumeName: pv-plex-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-media
  namespace: media
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: ""
  volumeName: pv-emby-media
