apiVersion: batch/v1
kind: CronJob
metadata:
  name: wotlk-weekly-restart
  namespace: wotlk
spec:
  # Restart at 00:00 every Wednesday (Australia/Adelaide).
  # This job starts at 23:30 Tuesday so it can announce for 30 minutes.
  schedule: "30 23 * * 2"
  timeZone: Australia/Adelaide
  suspend: false
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 2400
      template:
        spec:
          serviceAccountName: wotlk-restart
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: NAMESPACE
                  value: wotlk
                - name: SOAP_POD_LABEL
                  value: app=wotlk-accountmgr
                - name: SOAP_CONTAINER
                  value: accountmgr
                - name: WORLD_DEPLOY
                  value: wotlk-worldserver
                - name: AUTH_DEPLOY
                  value: wotlk-authserver
                - name: ANNOUNCE_PREFIX
                  value: "[Server]"
              command:
                - bash
                - -lc
                - |
                  set -euo pipefail

                  ns="${NAMESPACE}"
                  label="${SOAP_POD_LABEL}"
                  container="${SOAP_CONTAINER}"

                  get_soap_pod() {
                    kubectl -n "${ns}" get pod -l "${label}" -o jsonpath='{.items[0].metadata.name}'
                  }

                  soap_exec() {
                    local command="$1"
                    local pod
                    pod="$(get_soap_pod)"
                    if [ -z "${pod}" ]; then
                      echo "No SOAP-capable pod found (label=${label})" >&2
                      return 1
                    fi

                    # Execute SOAP from the dedicated accountmgr pod (has PHP and SOAP creds in env).
                    kubectl -n "${ns}" exec "${pod}" -c "${container}" -- sh -lc "
                      set -eu
                      SOAP_URL=\"\${SOAP_URL:-http://wotlk-worldserver-soap.wotlk.svc.cluster.local:7878/}\"
                      SOAP_USER=\"\${SOAP_USERNAME:-}\"
                      SOAP_PASS=\"\${SOAP_PASSWORD:-}\"
                      if [ -z \"\${SOAP_USER}\" ] || [ -z \"\${SOAP_PASS}\" ]; then
                        echo \"SOAP creds missing in container env\" >&2
                        exit 1
                      fi
                      cmd=\"$command\"
                      SOAP_URL=\"\${SOAP_URL}\" SOAP_USER=\"\${SOAP_USER}\" SOAP_PASS=\"\${SOAP_PASS}\" SOAP_CMD=\"\${cmd}\" php -r '
                        \$url = getenv(\"SOAP_URL\") ?: \"http://wotlk-worldserver-soap.wotlk.svc.cluster.local:7878/\";
                        \$user = getenv(\"SOAP_USER\") ?: \"\";
                        \$pass = getenv(\"SOAP_PASS\") ?: \"\";
                        \$cmd = getenv(\"SOAP_CMD\") ?: \"\";
                        if (\$user === \"\" || \$pass === \"\" || \$cmd === \"\") { fwrite(STDERR, \"missing soap env\\n\"); exit(1); }
                        \$xml = \"<?xml version=\\\"1.0\\\" encoding=\\\"utf-8\\\"?>\" .
                          \"<SOAP-ENV:Envelope xmlns:SOAP-ENV=\\\"http://schemas.xmlsoap.org/soap/envelope/\\\" xmlns:xsi=\\\"http://www.w3.org/2001/XMLSchema-instance\\\" xmlns:xsd=\\\"http://www.w3.org/2001/XMLSchema\\\">\" .
                          \"<SOAP-ENV:Body><executeCommand xmlns=\\\"urn:AC\\\"><command>\" . htmlspecialchars(\$cmd, ENT_XML1) . \"</command></executeCommand></SOAP-ENV:Body></SOAP-ENV:Envelope>\";
                        \$auth = base64_encode(\$user . \":\" . \$pass);
                        \$ctx = stream_context_create([
                          \"http\" => [
                            \"method\" => \"POST\",
                            \"header\" => \"Content-Type: text/xml; charset=utf-8\\r\\nSOAPAction: urn:AC#executeCommand\\r\\nAuthorization: Basic \" . \$auth . \"\\r\\n\",
                            \"content\" => \$xml,
                            \"timeout\" => 10,
                            \"ignore_errors\" => true
                          ]
                        ]);
                        \$r = @file_get_contents(\$url, false, \$ctx);
                        if (\$r === false) { fwrite(STDERR, \"soap request failed\\n\"); exit(1); }
                      '
                    "
                  }

                  announce() {
                    local msg="$1"
                    # Best effort: don't fail the whole restart if an announce fails.
                    soap_exec "announce ${ANNOUNCE_PREFIX} ${msg}" || true
                  }

                  echo "Starting weekly restart countdown..."
                  announce "Scheduled restart in 30 minutes."

                  sleep 600
                  announce "Scheduled restart in 20 minutes."

                  sleep 600
                  announce "Scheduled restart in 10 minutes."

                  sleep 300
                  announce "Scheduled restart in 5 minutes."

                  sleep 240
                  announce "Scheduled restart in 1 minute."

                  sleep 30
                  announce "Scheduled restart in 30 seconds."

                  sleep 20
                  announce "Scheduled restart in 10 seconds."

                  for i in 9 8 7 6 5 4 3 2 1; do
                    sleep 1
                    announce "Scheduled restart in ${i}..."
                  done

                  sleep 1
                  announce "Restarting now."

                  echo "Restarting deployments..."
                  kubectl -n "${ns}" rollout restart deploy/"${WORLD_DEPLOY}"
                  kubectl -n "${ns}" rollout restart deploy/"${AUTH_DEPLOY}"

                  echo "Done."
