apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - privileged-namespaces.yaml
  - runtime-hardening-workloads.yaml
  - mutable-image-tags.yaml
  - chart-managed-workloads.yaml
  - gpu-operator-workloads.yaml
  - wotlk-latest-tag.yaml
