apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metal0.yaml
  - metal2.yaml
  - metal3.yaml
  - metal4.yaml
  - metal5.yaml
  - metal6.yaml
  - metal7.yaml
  - metal8.yaml
