apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: metal3
  namespace: longhorn-system
spec:
  disks:
    default-disk-1030800000000:
      allowScheduling: true
      diskType: filesystem
      path: /var/lib/longhorn/
      storageReserved: 76087874764