apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: metal4
  namespace: longhorn-system
spec:
  name: metal4
  disks:
    default-disk-081400000000:
      allowScheduling: true
      diskType: filesystem
      path: /var/lib/longhorn/
      storageReserved: 81786094387
