apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: metal8
  namespace: longhorn-system
spec:
  name: metal8
  disks:
    default-disk-1030400000000:
      allowScheduling: true
      diskType: filesystem
      path: /var/lib/longhorn/
      storageReserved: 74288453222
