apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: metal2
  namespace: longhorn-system
spec:
  name: metal2
  disks:
    default-disk-1030800000000:
      allowScheduling: true
      diskType: filesystem
      path: /var/lib/longhorn/
      storageReserved: 76087874764
    extra-disk:
      allowScheduling: true
      diskType: filesystem
      path: /var/lib/longhorn/extra
      storageReserved: 21474836480
