apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoiceninja
  namespace: invoiceninja
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: invoiceninja
  template:
    metadata:
      labels:
        app: invoiceninja
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1500
        runAsGroup: 1500
        fsGroup: 1500
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: invoiceninja
          image: invoiceninja/invoiceninja:5.13.24@sha256:e94b961c4c1158c591213480624908c2f7276c733d51957523bbfb5158b7ae43
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
              name: http
          startupProbe:
            tcpSocket:
              port: http
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          envFrom:
            - secretRef:
                name: invoiceninja-env
          env:
            - name: TZ
              value: Australia/Adelaide
          volumeMounts:
            - name: data
              mountPath: /var/www/app/storage
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: invoiceninja-data
