apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invoiceninja-data
  namespace: invoiceninja
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invoiceninja-mysql
  namespace: invoiceninja
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
