apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restic-cache
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
