apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-mop
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: apps-wotlk
  path: ./apps/mop
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
