apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: "s3://cooked-k8s@us-east-005/longhorn"
  credentialSecret: longhorn-b2-credentials
