apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - longhorn-helmrepository.yaml
  - longhorn-helmrelease.yaml
  - default-backup-target.yaml
  - recurring-jobs.yaml
  - settings.yaml
  - weekly-backup-retention.yaml
configMapGenerator:
  - name: longhorn-latest-backup-retention-code
    namespace: longhorn-system
    files:
      - ../../scripts/longhorn-retire-backup-history.py
      - ../../scripts/longhorn-upgrade-engines.py
