[authserver]
LogsDir = ""
BindIP = "0.0.0.0"
Authnet.Enabled = 0
Authnet.VerboseLogging = 0
Authnet.AllowUnverifiedLogin = 0
Authnet.LoginGrantTTL = 60
Authnet.StartupModuleSeed = 0
Authnet.BindIP = "0.0.0.0"
Authnet.Port = 1119
RealmServerPort = 3724
LoginDatabaseInfo = "${DB_HOST};${DB_PORT};${DB_USER};${DB_PASSWORD};skyfire_auth"
LoginDatabase.AutoSetup = 1
LoginDatabase.AutoCreate = 0
LoginDatabase.AutoBaseline = 0
LoginDatabase.AllowUpdateHashMismatch = 0
LoginDatabase.SqlPath = "/opt/skyfire/sql"
LoginDatabase.WorkerThreads = 1
LoginDatabase.SynchThreads = 1
WrongPass.MaxCount = 0
Appender.Console = 1,5,0
Logger.root = 2,Console
