[worldserver]
DataDir = "/data"
LogsDir = ""
BindIP = "0.0.0.0"
WorldServerPort = 8085
RealmID = 1
LoginDatabaseInfo = "${DB_HOST};${DB_PORT};${DB_USER};${DB_PASSWORD};skyfire_auth"
WorldDatabaseInfo = "${DB_HOST};${DB_PORT};${DB_USER};${DB_PASSWORD};skyfire_world"
CharacterDatabaseInfo = "${DB_HOST};${DB_PORT};${DB_USER};${DB_PASSWORD};skyfire_characters"
LoginDatabase.WorkerThreads = 1
LoginDatabase.SynchThreads = 1
WorldDatabase.WorkerThreads = 1
WorldDatabase.SynchThreads = 1
CharacterDatabase.WorkerThreads = 1
CharacterDatabase.SynchThreads = 2
WorldDatabase.AutoSetup = 1
WorldDatabase.AutoCreate = 0
WorldDatabase.AutoBaseline = 0
WorldDatabase.AllowUpdateHashMismatch = 0
WorldDatabase.SqlPath = "/opt/skyfire/sql"
WorldDatabase.BaseSqlFile = "/opt/skyfire/sql/world_database.sql"
CharacterDatabase.AutoSetup = 1
CharacterDatabase.AutoCreate = 0
CharacterDatabase.AutoBaseline = 0
CharacterDatabase.AllowUpdateHashMismatch = 0
CharacterDatabase.SqlPath = "/opt/skyfire/sql"
Console.Enable = 0
Ra.Enable = 0
SOAP.Enabled = 0
Appender.Console = 1,5,0
Logger.root = 2,Console
