apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-smtp-auth
    namespace: monitoring
type: Opaque
stringData:
    smtp-password: ENC[AES256_GCM,data:CxFzCeUNf24KA/4A9xEklg==,iv:lrM2qGY67Orwq1HNT/qNtOMkEzf3uc8kR8CQrXrATpo=,tag:b7FXavkOE6t9DSiiohhoxw==,type:str]
sops:
    age:
        - recipient: age12zt98j083qhangw8wg3zhy5zccp6qpw0e677m5jncgdmp94a84rqzvedat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVDVtdEtCdDFUNWxueFh1
            aTdidURIb2dwMjBXb2puSDZRam8weE9hdEVJCkVTTHBaQitSQnNFczBEWHdnVkVI
            QUcrNUZIWUR4ZXlMRG03R0JxYWIrYmcKLS0tIG1aWjh4SkU1d2hZYUVRZHU5dUVJ
            TDNDZW1TcFB1ZmQ3djNJdkxQbWVaUmMKN2+8SZtgcr0fSBaRoc3IcDzSxyMtAYXx
            ZZCsAdwKIELFiI+7M8ADGs4Ez/hFEqqOddSXJtqmJelU4tBeSZMdBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T04:48:37Z"
    mac: ENC[AES256_GCM,data:3yVUwORXYRNs6V62gMcn6yVN2gxjzL2DyPV0JS32VOMnuI0aBQavviQZhmS41UArMi/A+OFnq3+9wTXlyNTsQBVFGIlHo7wAWvnM5SFbvLsw4Aps2fMCo3sfbsvhJv8HL6nj7WbB1kJckCr+HM6rCG6pVYN7x13fkXoOUCFAkQM=,iv:Xz7MYnN3wmmyMsdSlwoem32aOQGt9EeRz2FL0SqEfko=,tag:Rvpk3PMbPAsNfKPgVnAsnQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
