apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-config
    namespace: monitoring
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:XvpSJDj0puI0qWEsq8jUkbwVWLCel89a9PBf7lN8fjTBS2MCPm8XH295hAlOoly0iGVb7eQABNrWIPtIMgnelNuQP4Nh/4KGCjDtNBcxpQYzk2AZHZQ5hhj55b4+OPNis0+QszapGYNe/6dSe/SKZnk/ALH67M7NBK9krPzhNmyhlgtwlPp2Qc9b32ljDj99rkq3YwtW2h7FZbleAfPGlR+4uwdJA+T597iaMC8obK2Hougr0LMkiGso+cBUg4HxSYG1i26RJCNpAGjGtBhse+zOQDXGyMm5QbZ2sOM57wWNZog1r3h+3C7hLvq5YaDhZOms3q2M8PCGYTWFiFmlnpcyOToYeZLj1YVJ23xD6YlMcMs+GlTSI2AB3z5dtkvnLNXf2bAgpmGolMnjv8QfXn75GoAPz/jXNqBb48YDKEYSdF+DFqmqB5C3VDjtrD9zAEjEhelA+gGuNNHA/VwNi/6053N0W3Wp9fHc0qKQpuw0FR4ro4j3XlNRDEdac3xQ+7ds8+WkHor4AbxQTo6VQpBRYxhVAr8m6GQZ2eIRmwmsSe+YOSKTKXQ0WdkpDSMBUe48nCGVg2pMg6+7cfCBWvnHqvVHJFuqpkAaRlE9c38hkfdGwZMGLBL52Std4iZ5QF35Jqu86sAB3RHIL4/lDXIdTSR9ZGgWpK3/h1ziUt90zvyHbIjd02IC3KoFfejZJmj4JQt5hiakY8m7pK4eA6JMOE1IGXwkhHKdtTh8WCpAKxF7PWDTSHDt814QyRoGnk6ygikit3ZETUIMhj7O/ZYrGptqJGGsckaASIn/PMYvP6tW8eecye80WgVE92gcPwkyKUd/abIbryIMY+By9/Jtplk0uubNfw==,iv:vsDdk2LAzb+fvPGkoSm3M7BKDvh//gW0jCkJ9wIbim8=,tag:Kj00yIoOJtkfN9M7fWDrig==,type:str]
sops:
    age:
        - recipient: age12zt98j083qhangw8wg3zhy5zccp6qpw0e677m5jncgdmp94a84rqzvedat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWWJLOVo1dWh5WDlrcytw
            d3ZBYmY3RW9qTUNBWVJ6QlpMaHJGSVNROW5FCnBmSkY1Q2RQV3FaWTUxMG90Y1Mx
            VkJNcTdvQXRBZVpOK2J3a25pWXR0YUEKLS0tIFhGYllUbExLZlpjNjRieEtOekFl
            RnYrMVF1TWRTajBlMk1MbkRCZFkySDgK+IXeLc2cr5vdnuheqRJK2WMs5777y6T2
            0TVna6iah9aa01m95gEzKYMThhjjv8QIph8ihw/wzlkkvxJjadOY7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T04:48:26Z"
    mac: ENC[AES256_GCM,data:TCkjf7Ajs5qVqjCgU+WjcpmItX4MZajtscbDEBeZ0uE4jAyarQEO2gbI66+ZquLMsgCK7bsM1D/i4TPaY/8HrRWAxaOZUDi2KclHdV6ekEPfkiAD/dkvEVTeYsHlrp27AS3xFSyaxrLzGHiJP34yC/Qy32QnM4H7+bVFFPmzYCo=,iv:FTzeue1kbw0bVbrmu909ZwW7dyme1oGd0gHdfIqzkQQ=,tag:YhwvpL6Bjeb5Y9sSHvDiSw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
