apiVersion: v1
kind: Secret
metadata:
    name: gatus-github-token
    namespace: monitoring
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:IM80dBGnqjF44FEoPhd35EnKjaOd9W3+uzdC30dB4uOLtpN1HiZJysb4ItaEXt8M1GZ1JwwiitoqwUNu38rIFWjeV5tJ75nf7UWjcXQw6pslBG8gcojEbD0f2eoc,iv:z8ZKvnGHkhrtYmonCqsnQ1FDHspKM/G176qu/F6mWgg=,tag:+gavHP92/V5cjX/dtvN6kA==,type:str]
sops:
    age:
        - recipient: age12zt98j083qhangw8wg3zhy5zccp6qpw0e677m5jncgdmp94a84rqzvedat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbkNwVTRtY0pHSk1sS0Vk
            bmtTS3FzemRjakF5dHBEdHREc2duL0d6N1FzCnJnRVBKeXdwd285eVdCbzh5MGVx
            ZyszTGFyak4wYXlyWkZXeE9DQW1xcW8KLS0tIHV2SDhud3Y5R3I5NWxHZ3dlazkw
            bXZ0OEhBK3Jpd0p3SWhOVWJhTDJLZFUKYRjx3FK14xJJoc6TeBURTwnUAwspO/6j
            0rE6tUCOxFUNIpP1IC3SoCbsRMzyBXv9YKrxflp97X8rGXnfYCSLWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T03:04:33Z"
    mac: ENC[AES256_GCM,data:QkgThV4I/hmfGfKxOhWJiZ588H/PPK0kIQnGaV3kufOpFAsP6+FNX0NsVa+v8Y0bZ/U25N8LFK5D0U6Xj3n3KfHd2+16pOry5CsbHPCH3HaAYuBteyjnBWAkke0tv06y7g2lYvXRB7JOma7bFtzpumEqmD5O45hJnFT8q7SfZT4=,iv:DiXmtSGjExbqzT2cs5Crby8iMpxlUE4YU6XsZofLLBA=,tag:IHS2MnL45Z6MUfV6YEEKMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
