apiVersion: v1
kind: Secret
metadata:
    name: invoiceninja-env
    namespace: invoiceninja
type: Opaque
stringData:
    APP_NAME: ENC[AES256_GCM,data:kozr7PbBQD+/pycwyw==,iv:5nnh7KEbVf9jCd7adQLvued9qnBlCGXQiBsiOOzxWqo=,tag:vKgDhwytSaMapbAZl4wTxw==,type:str]
    APP_ENV: ENC[AES256_GCM,data:Q/Pq+LnaRu6nFw==,iv:n4kpabYBsfslXoCUUvGM7Fj+ETPXabh5f+xZzAeGVeI=,tag:c+3nTkoczSXUhUUChew8uQ==,type:str]
    APP_DEBUG: ENC[AES256_GCM,data:13GDGYA=,iv:s3PmaPTi4sp3WY2MqDdWM/41T+EojITi/qZaYp1V+TE=,tag:eawdiYkWuc4z+m+BB3vTRA==,type:str]
    APP_URL: ENC[AES256_GCM,data:Bboj552cuXKpPYg2pkhqMo/VZ2eW4mxnQkki,iv:sIVhKlnDxN99QWKQdCx8A6shX3DiqA1r01ouhB8UVVQ=,tag:Q6rDK4hBaXio+ke07UKtOA==,type:str]
    APP_KEY: ENC[AES256_GCM,data:G04UJE2B/darO+ywQk8HRmU2PM+qJqYF9JxymwpB1DQcMgkw1Qz/nOkWYHVBykaFdVZU,iv:ATA3142dAd7LVTgt252pZPeNJsnz1y7nGysyr5164vU=,tag:rtFBKJAwTEuSEmN1mlMpSQ==,type:str]
    APP_CIPHER: ENC[AES256_GCM,data:6lb/6nGDm5Y/E38=,iv:COPmU9DMFojOIGdjr9pFcf0opzaaC17HhbxcXsjfKKQ=,tag:92pr0fVo6CNvpzSIUK8KEg==,type:str]
    REQUIRE_HTTPS: ENC[AES256_GCM,data:JpHZIw==,iv:294jkKf/8R6/LRc3pFuGXgAQ6SQKCPMP2bY4zGfVd+I=,tag:6bLxkXYANJN39zDIq/e1Rg==,type:str]
    TRUSTED_PROXIES: ENC[AES256_GCM,data:Mg==,iv:Aw9WtH+YwG9jk7OelN1Gzm2yTvvnZVv+zPRnpZjnKow=,tag:23bkHr/ZD+CPRuhRBFAMkQ==,type:str]
    DB_TYPE: ENC[AES256_GCM,data:5rDlHK8=,iv:jCJo7X0Y4O6L3Xxc81QdV6LDd6Hs5M73ibtNjGUcfVc=,tag:xNt0wvf/81QK3Oa/Lu8UZA==,type:str]
    DB_STRICT: ENC[AES256_GCM,data:4eAG8u8=,iv:1p5dbWnGIRv5Jzxiy2xtQMD060Co6ZfBvu4ko3kxT3w=,tag:r6cgzJyB1W9Y80U7dC1gog==,type:str]
    DB_CONNECTION: ENC[AES256_GCM,data:Zi1Lmn8=,iv:NqSg/nKdHzMh7QXH4KOws8xivBwZYgiR/2GMFqt1C5E=,tag:Kp7Qf3nmnAiPkNlzrHZQig==,type:str]
    DB_HOST: ENC[AES256_GCM,data:53YxTFJNRpskRpIR/HbGSCRy,iv:14U9OENbN7vSHGbPZgTFT+jai/bhaaaGwzBeaYaIEag=,tag:jP8KMKRmKdhIB42ojF06kw==,type:str]
    DB_PORT: ENC[AES256_GCM,data:CMFHzw==,iv:6fJ4/AL+INlKBQ3r45bTcybLo6DlbEcqbZE2Zv6UjIQ=,tag:lZFr0V2COCeV7HmxAz/9ng==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:9NhhVns=,iv:xoqg0bIqwombpvQlXfbaOKlkzoVCZ9859dBPUnoEJeE=,tag:C10wUnBv6CGP9BWve9lZjQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:iNa9gOc=,iv:adgKdXZhNJ+jw6oYyVZ6Cu+L/swtPCWZwe2llXdboag=,tag:PeUqKCwMoqW/1ImzRD7cag==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:zYM+oobVkjFY1cXtEUUEJppdUVl8ja+EXWG9ADvI/c+Efo33310GxUJRchKADeLC,iv:yh92R9e29ckLF6aHkjtoKgF/p7zTnqPi8ru5oG5dFc0=,tag:kiRthjOKFzcD95acFcqqkQ==,type:str]
    DB_ROOT_PASSWORD: ENC[AES256_GCM,data:9v95uJJgqzDBkzzV8F/Of2giaUmg5qYeGBGpKKmpQ3fPnME8CM43gbuaEob8Dvk6,iv:SGM5tDgfW/ZJQ4bpI0lijnoxrUvI/qlMnHJeBcgkoRE=,tag:nZmXVky9xCtebQqHmObjIw==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:klYrhZxvDOIZg54FqaWYeIkDLAHEkVjkpN6p9EfkXdQIDmssBcJqkoA072QPC706,iv:fL6h8/GIKVnR3/LKeGuCIZCJ1TsOdaInh7TVr6p0FAU=,tag:JCgqVi7O5rfZQDD8EXOrNw==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:8gKNoW7ebvUhxybNZDUuLUll,iv:Q6Pvg7f0CzK/fo0LWadwYJlPdTBqkJpQwUht/x/SFnk=,tag:jpDzFSfTtvxn+RooWHwtOw==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:Zt7znA==,iv:3A4IaR4xBu7S5wz8uGk+jDyzyUZ/Fk1OQZsmXNPV6J4=,tag:WyUyB68UpN7rrVT0ZYiIHg==,type:str]
    CACHE_DRIVER: ENC[AES256_GCM,data:ylEmFVE=,iv:8HJydjlav75KhnwXNCYgL/WJNPSTqDTyY7BtIR7ot3A=,tag:n23tZoVmKYCat5m/AElTDg==,type:str]
    SESSION_DRIVER: ENC[AES256_GCM,data:dYe81pA=,iv:cVn4Ne081pdAhgy85LhS6BKsSPpxhiGRQSrqJ2ZlC7s=,tag:5icNsRBnvR/jDLUb7Girhg==,type:str]
    QUEUE_CONNECTION: ENC[AES256_GCM,data:HnmfBS4=,iv:1naQu/9zX2rfi64Va3SrsnWqUIqtPk4+PjduZlAsAvM=,tag:aIHon9h1KrmRr+k5MS5qXQ==,type:str]
    MAIL_DRIVER: ENC[AES256_GCM,data:O2nM,iv:OVGzCkhSuBkuvjY/swgPDxszv9ySGmIlTC2jPch5TCY=,tag:o2Aeksv5S2279IQfP3Fj+g==,type:str]
    MAIL_MAILER: ENC[AES256_GCM,data:r9/p,iv:Gbxj86nx9ad0eQr9c9+YATO3ZDwzZDL00VgvmTPSVVQ=,tag:S5PNbg9mfi0tGBQhJKURLw==,type:str]
    MAIL_FROM_ADDRESS: ENC[AES256_GCM,data:vbYEN6IEaeZHOY/UGO8c4hBrUJYTC/xS7Q==,iv:OT7U7C/uF7Y1+J0Iq4aPAaZbOiETgTbJ3AUORWbTbic=,tag:fTykleBp3h33627llQR0Bw==,type:str]
    MAIL_FROM_NAME: ENC[AES256_GCM,data:DCD7gXFQ/JzRgL+Ovg==,iv:uKuAwpCEMRkPnZ9SX/r1l/5vRT6YnyliwZn5XfrVzdA=,tag:fsxxQGKYDzFTV/aICmNUyg==,type:str]
    IN_USER_EMAIL: ENC[AES256_GCM,data:wDVzyzKRwKGuEdCYGtSAHBHKFt+gaRvidQ==,iv:jBDqALWy7LyoJTAJqNqsC6h8vM4fQ6eXIA3bICh3Wp4=,tag:2VH/itOccIg7xAs+ybZJHQ==,type:str]
    IN_PASSWORD: ENC[AES256_GCM,data:2HJ+8tQuzBtZz5+db2933y1RYFi4jw5mUFWbR1gz5gA=,iv:QgUJiK01EucA77egrAhiOIwA4OTipQDYkqPKopCRQh8=,tag:WqbQpouTJl1RQ1yg6aQnvg==,type:str]
    UPDATE_SECRET: ENC[AES256_GCM,data:fR+VHeEKwqK+8BGd2hDRZdwXfmmhhgli4ew1rMHG7Dq9JwxZot3opU4sF/PDtjGHYMukQ9LhdTQ1eNQAc9p/+g==,iv:wd6ANMrSwK6w+VNrmy9OIOSnlgzsyltrHGy1u/sdhxU=,tag:cazDg4Bcllx7qGCjZhfnrg==,type:str]
sops:
    age:
        - recipient: age12zt98j083qhangw8wg3zhy5zccp6qpw0e677m5jncgdmp94a84rqzvedat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGV091bFNRQXRhd0RZdFdH
            L1dLeWs4b3R2dnJjc0dqdTFQZGJQUkJsMVJjCkZOZjNDTytNMmU4d1NSUVZWUXhD
            eGFHUGZ3Zk5uaTdLZWFpQnplL2lmWlkKLS0tIFhXSTlZZ1dJQi8vNldIT2NLbVFn
            OCtVRW4rSEIvZkhnRHJIdml6NER6TE0KkuMpMfWTq3C57Kdnl2TeJ3y60OAcmrhO
            b4qnYjBLGBxr46dUhqB1Khaj5bbS+Uy18tOWJhGtmENwMQNLPrTmVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-09T03:00:23Z"
    mac: ENC[AES256_GCM,data:/xuoJ7yWvk0iU4+YCNhq7+ARb5kpnoW77+qiIMLLwTYuqaLI2cuQaMUzXCWxKuZvqmMcaKJTi5kmsNPK9auurdJpFPvsa5ADX7f2u4WHaNEam4Y1O9HXwW7fNvY3HLQZ6iZ6n5W2gQOOed5f/SIB1cXuyDdGQw+Xx8TBJIoL9Ks=,iv:sZE7Er7OG5nNehpnOK1PqLk+8RQ9UXt732kE6AHZm9c=,tag:WOUaIbE9u9Y65r2S1516RA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
