apiVersion: v1
kind: Secret
metadata:
    name: longhorn-b2-credentials
    namespace: longhorn-system
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Uk3Aa4C4qMCsFsAOcpYIczi2ToMl8ayB2r7pZiYmjxsHaGU7,iv:4V4jDipHqoChHAW/R9SjXejBIoGVRhdqp/nnEV/XRjE=,tag:rU8dmCKl8yfR7/laAWwLcA==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:+nxVThdLa8TQc4N2HPhDhdyhrlJDUSXTf7a6lff6YvyTJ2kmI4bToenrdf6t4iA7zEquOA==,iv:b0hvRWcqMdU3AuUdhsLiwYiU/ico4jtrfIRXBvdAXHk=,tag:HPDESM0M8rp5/xc01HHszw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ALA4GfWBE2gmm4+lb8RArBtK1cDDD8FYgJV8GppEVsj1TmADF+XXI2mifdI=,iv:96E75PH/9MGWm/Db0avAhmrIXzRIYxzyAzBYZP51yDY=,tag:zZtTY15sOjuRyCTz4a2Jlw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWd3lmMm9COUpIbkxUdTQ3
            RjVXcXJ0NmlvdXhRSTdyUkV6am1jN3VSdUVZCkdranV3QmNBSzNsMzV4Um44UDJE
            SEZleEphajZIUGZSZmhsNVU1dUFYcFkKLS0tIDVPMVZlM3hwUUtIaGMwVUQrT2t0
            cnhScEh5ZWtrT3lxem9CbVhxVXpHVkUKD7N0P3gbhfz42U2j4Ah0ccocrHpuNwef
            Mx3eg1o4/Nfjk5gTUOHH7NTci0ehQCTMWTS6ntVNXj4Yt6VOJ6FHeQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12zt98j083qhangw8wg3zhy5zccp6qpw0e677m5jncgdmp94a84rqzvedat
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T23:27:43Z"
    mac: ENC[AES256_GCM,data:9GiyqW9MwjcIXuAzpI58SEXIlsZd2jTA4clRDoTxxwGXjMeX2oOdplxwXI9txjMT524TRcnu/aDCSLNLTMD4uw61Pry94tVb2zJXN2CR/z4VgtBdirHaZFF92QH8FrgnqheT4bhZBnkIBdC41ZbwvrbtepPZT8gQPlaCMNuLlYA=,iv:Dq78BEvVNrHUKBzb4tdj+otunw9+k498yJEFDYacSIs=,tag:hBC7m95+BVENwicP3RQhlQ==,type:str]
    version: 3.13.3
