apiVersion: v1
kind: Secret
metadata:
    name: skyfire-playerbots
    namespace: mop
type: Opaque
stringData:
    AUTO_CREATE_ACCOUNT_PASSWORD: ENC[AES256_GCM,data:3DXl0F+DqK26lqCHKuKFNw==,iv:oNlfItC2ojoe8uwAt1DGRYW1pH0+0RJL7JJ3gVQa7z4=,tag:m8OIsi+Vv18TXiKeq1VWMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12zt98j083qhangw8wg3zhy5zccp6qpw0e677m5jncgdmp94a84rqzvedat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdk9QMzkzZ2Q1MUFJQ3pw
            anY3bTNvcmsrZm5zT2c3b3Y1WnQyK3laMmg0CmlkU0R6NEdaODk2ZDRybXY1VkRO
            TnhUMHZseFpPWkxrWXlKUk00dWQ2c1kKLS0tIFI2dTFxcjQvM1NIVkoxYzBtM2ZT
            QUZ6dHY5NEd0MkZxOUpudFhvbC94ancKhRRRp/eNTHgWWs7vMwP5orvb3b5a22tu
            xvHpWB9s4pflhR3n/JeNwxa/JQq+TgrzKOA8+EsvG+TD1IiVAkaLww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-22T12:31:35Z"
    mac: ENC[AES256_GCM,data:qcAHVpCrB3l0MUhMQe+PiyH9Fj8qGxZ5jr1PIdT63tKNd3yva8pxvgcRVOHDSrTJ0RjjfrT+ThDUOyBiQnODxPBw92o7Dn87bubAZhJZvu7iKtBqpydJUyhZi7CWuXtLZq+w+wzegpT196fZaJt6N5zmk/4MX3ODXCuEL2IdDB4=,iv:NDGrlpa1zekE7S8c84frprilFRIvfDez+pHVKKAAb/w=,tag:uC3VoAhqsC71XEUm4ykwxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
