apiVersion: v1
kind: Secret
metadata:
    name: mop-mariadb-auth
    namespace: mop
type: Opaque
stringData:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:wCoR8x5+HrLQf7zpD6I1sGW1RYXV8WOeGppnRSxp7Z6irpItX+12CE84Q/NOXr43cVoTqOo1uZYWVyLLWq2hxQ==,iv:DRMwnxSjROXr7NuqdQJFAD7hrYVPrqTsy9zOhmXqGvY=,tag:Wp7Wxp+SrPhiAfUVbv1MUA==,type:str]
    MARIADB_USER: ENC[AES256_GCM,data:BOVR9dMYeQ==,iv:wfdDtHVxJ7MENnVA83JnVTc1N11/lYFH2mja6d4/GqI=,tag:LrXMpm8rgd7vnU5KrTMWQQ==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:bzj2Z5K6T5bnp4xZ3OX+OJuNA5exwgRsIvgxh76kAjgQu5LS0poCdJnDbAZKAOS355TZyQJcGh9JPhoiphSGSQ==,iv:kz/hNgqHGFvWu4VYQTUjl868eAWlB351srLR4a7gJCU=,tag:RebpbjM+qzA0MgTFYXUhaA==,type:str]
sops:
    age:
        - recipient: age12zt98j083qhangw8wg3zhy5zccp6qpw0e677m5jncgdmp94a84rqzvedat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNHRRNlZwWS8xSUhBMTYy
            Ym9vZnZRRzF2TVY3V1pIV1hadTZ1aC8yRngwClZCbUhaRFM4Tk1JYkJ3SHNqZmVu
            eXl1L1I5Mnp1aGhTWUhVZWpPdXVXUk0KLS0tIDBSblZhRnhDeTVTdGpkRmw5RHd1
            TzZQQ0Z3UlZHbjNxVG9mRXRxbUdXSUUKza5goBex4bFBZ0vYBc24Q/lK0Cl9HNKh
            7QTskgU6uqszgFhQqmG/CNIPLtgc4cHdY/xIxyJLCEb4/j88zBKhiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-22T08:34:59Z"
    mac: ENC[AES256_GCM,data:d9uQEirLvttEg8MeWHAloC38DW3P4TjmfhJZ9GjvoDjjWosS60HdHFt18EnnrstbILITblF/L6SND/jE9/qHaX/+DyeCXjgeXf+E08vwHcQgLRPgA7WokUqFIOatp563JIewUyTwUlgJBxXItJMo1OSybdpMEtW/HYMPLMdE27Y=,iv:Ax/0fp3PT94f4LDb4W8SOzi8/lyNtUX/0SSUv/ZBDzk=,tag:lmNJTipFz4UPZ/B4h7Wycw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
