apiVersion: v1
kind: Secret
metadata:
    name: skyfire-playerbots
    namespace: mop
type: Opaque
stringData:
    AUTO_CREATE_ACCOUNT_PASSWORD: ENC[AES256_GCM,data:xTiO+7y7iSYRK4TL+eqjVA==,iv:0C+qBMQZcbO6ib/EM33EVoUMwE2WmOYkJfmGgvlYd8Q=,tag:C21vt8XAdzaH5bcZTUph0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12zt98j083qhangw8wg3zhy5zccp6qpw0e677m5jncgdmp94a84rqzvedat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdDJLWmhkV2Y5dHRRSzgv
            YklIbGxYNHJKNDZlWjQySUpKaDROOFFVRjBvCkNvbGhwQlJtelpoOGJBTU15QVU5
            RW9rV3ZoQkJXbWg5NldLM1AvNU9vRzAKLS0tIFIwaXhDSHMvaERJV0lIejFxUWhE
            cmMzSmpSOFJNSkxLVWR0TVNSZ3hVMlEKuCevjNTDsIp6CCFOyUNzaZ/2PPJZqaxC
            7xYXMQFkEXwqGmrFJxv9J2gcsKLMfTpy+Gqjmm8nGttO1NMAv6VWfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-22T12:18:13Z"
    mac: ENC[AES256_GCM,data:XrQ8naQRHHyv6oLd5F2acsUq0ctKigq6tgEWHElEwY2ro1LWqpnXTqaX+gfSHNyPVUawdV6I35CHdBifj3iKD7HjITqxOifcUnI81YuPRXH90oKK5VT41UdtgyEjQXUhyARsakS3gbPo3K4dD5GEZ5Vj8j03h2OnH+tX/HfGjOQ=,iv:XHe1OS5tvBiIu6HbBmp69/BNSUzLB3NJkvL/3mZNX6k=,tag:bf0TTzguf0tZIFn8qkB+XQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
