apiVersion: v1
kind: Secret
metadata:
    name: skyfire-playerbots
    namespace: wotlk
type: Opaque
stringData:
    AUTO_CREATE_ACCOUNT_PASSWORD: ENC[AES256_GCM,data:gKhn0oNTbNhN5HRkQWddLnD2+M0ueeMPnaoSGTy9kBr8Tj4h3ce9x1ljUvXi9pyKDMQB9NWIAvuPwlLu5ofnpA==,iv:V3OYiPNSVxIDDb8bCG2A/T2s75svWlCmMQZm9lFOOD0=,tag:MXCTr9wBmcL//Cqxa1V1KQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12zt98j083qhangw8wg3zhy5zccp6qpw0e677m5jncgdmp94a84rqzvedat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUENQcnNoOTQyRTNiaXZk
            d2lKMFZRZ3FNVU5WMzJiSFhFUXloM2lwUG4wCnUvUGF0dGViaTZNOW40WUpXY2tp
            bEpLdVJLVDNaeG1kSm82cE92OG9iNmsKLS0tIEt5UWM0M1JSdEJGLzFmMThJMVQ2
            NTNvNFJpZzlXYUJFdzdyeDdrY2JzSk0KUm4mY0yR+YvDtfAmbOD4mYFFQS2LIvhc
            1I3Kwe3ntATQJ5EByp+FOglourq71g5nS2u8iDY0DyzcOjPZPP+yhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-21T06:38:12Z"
    mac: ENC[AES256_GCM,data:4wfTZe+5fsazgPqjjhw6eOwNDh+dn3sUu7+CDPxnNd+Wta6eykF4KH2/u2pd0gsyhH8TEmSW9dMmtba/ds91qlHjIwp2djJL037DVB+XLkqxDLkst5gdf79LpZdRwwyBFmUF1mt4QCL3x95MzHb5m8T4RGjprXTojku3KE1IOyE=,iv:GqpxnA9Fwmgvybg5uiPzdNMOMGic0jp2pBIgQOQwvQk=,tag:ierQQKl9qpTwRtZLw5gNtQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
