apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-sso-env
    namespace: security
type: Opaque
stringData:
    SSO_ENABLED: ENC[AES256_GCM,data:0JzGrg==,iv:af+V06KWWQZmUgS09tUxg3kTc+Rvs/Lrx/0vQ9s751g=,tag:Z2aQz4494DDnkAejt9PnAg==,type:str]
    SSO_ONLY: ENC[AES256_GCM,data:ZFbAnNs=,iv:Clgoq/lbqCyCZ5gkFbufG5Tb5ScCBRj1ysjf1T+5r9Q=,tag:upvP8n8Sl/rpM0zodcMdSA==,type:str]
    SSO_SIGNUPS_ALLOWED: ENC[AES256_GCM,data:+g2qDM4=,iv:zz3Vo9qVWnQACyh4EDBY2dQJr6npSYgkkq3T05v5qJs=,tag:G/cinL0gEsTy+60RAsVKYg==,type:str]
    SSO_SIGNUPS_MATCH_EMAIL: ENC[AES256_GCM,data:dkFw7w==,iv:Zh8MSjHlQBojTUN2eCUjRQmCAlZIb8wtRpN7HU0a4y4=,tag:lR4dglEFWeVnUZpk/uTqaw==,type:str]
    SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION: ENC[AES256_GCM,data:P7YeQw==,iv:5/udUkvSez11E9SrRjKLKERGqZ30nA1cPAQzvRXFm08=,tag:0L75O3MODuFf+thnxGuu4w==,type:str]
    SSO_AUTHORITY: ENC[AES256_GCM,data:cSzpHgmSqwAIi3/3uK3qACGmifgICLQn4bjk0E50myL6HPZaVlfhJbwSAq8ggtYB48o8yLkgGRFDpe1CELDwA8hNfSsz9XtSO1Fd,iv:5RrTzJam+Z281Wse4G8W7FPfo5AOK/GQBUkOCaWYCFA=,tag:O07ANneQb8tkut+zqbxMIQ==,type:str]
    SSO_SCOPES: ENC[AES256_GCM,data:hc/w+KeLVwyVzRdAY8+o+01IiAstL38Ml5iRRlPrkFohCDbJptv/,iv:Ct+N4ayjMXnRJCT4QcJEuy/h6IECQvzWkNhlxtOIaX0=,tag:s6isW5w6yghnM1lMej1ovw==,type:str]
    SSO_CLIENT_ID: ENC[AES256_GCM,data:QQA9Bw13PQJI+J8IQb3N3L/YLAvgpTKT3h3QA7TGB2Ll2ikW,iv:0N+6jNxJkQiK+KHdI0HqlgB4uUSH/943HXeWQWVOegU=,tag:BKx0x6MI6Htw5AoeeV7y3Q==,type:str]
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:Gi4A8w7le5NF98TBvhIWVIganMUGx5HkZ2UPEM05YcMclTaRONR6Uw==,iv:gsK+Dc3fwduByA8Qii7fWtUDRATjiXrB/svRGWbzm0c=,tag:Ap9G96ZPlzNpyRpKtkGa0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12zt98j083qhangw8wg3zhy5zccp6qpw0e677m5jncgdmp94a84rqzvedat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTzhDNXMvNjZWaDAvVXBu
            aVlIS3JTaWhFNCszQS96MmI4dnVZQlZXbms4CmVVZ3E1MVIzM0U1NkJ6TkNSYzc4
            NmlYWGZlRnN4dXBEVkNKcUlKQUEzUG8KLS0tIHY1YnB6a3grTnEvNDdNVW5nSGx2
            NTlLQ3BZTTc2b1B2SU80dEt1aG5SNTAKvp/bhL6UqMvxlJltCgjTCd0EfF/ykcCf
            L5KxEs7BqXlquXoJO3N6dlajRZGEXBxFWybzu0VmNK3rN4q5022etw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T02:52:07Z"
    mac: ENC[AES256_GCM,data:MQqVGnNWy0FUiYclwUEy3TnIUm4lIOnM/dWGQXcJJdYDxEgekaDBpVb9YV6/F/HcM+fXqnzN8QqtkzcqVogSH/YQAeAFGvo33V0NyeBcNifjm5ALIcq3MX5lvxfMH2gVN6SVOhGrikBv2JOXQpyO6K/FNkqUnHAjHgG5ykQztB0=,iv:vMnA0XKDPybWFOMAKNN3nSI2kislZcqZohSHhlgK6nY=,tag:VZ6/oTJInMcLyAyDQu0BAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
