apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-sso-env
    namespace: security
type: Opaque
stringData:
    SSO_ENABLED: ENC[AES256_GCM,data:BuDi9Q==,iv:CbbGHO3ZBLWUSJFe6HoQ0PNZN4jH8YEBqQ0aklttK28=,tag:Z92/T29DH3LwLwHRsp8R+A==,type:str]
    SSO_ONLY: ENC[AES256_GCM,data:4RsSNw==,iv:EOGamGByna83OrGw/IpEfV23Izjt7RbzrioAkm7Uv/k=,tag:4gtlsdfvAnshNYh8eKm3iw==,type:str]
    SSO_SIGNUPS_ALLOWED: ENC[AES256_GCM,data:gicSbus=,iv:9gwBqLp4JQcj9xbkDO0BOLhEotbNFea1bhvBvelpHio=,tag:9tPPINTAI8n1KboV8UXI1A==,type:str]
    SSO_SIGNUPS_MATCH_EMAIL: ENC[AES256_GCM,data:XlEOtb8=,iv:JjOkfP7+izDI7lr29JFNrmzgDNqgAwqASImopF8v8j4=,tag:maJSlcm99cc+TvGruoAwdg==,type:str]
    SSO_ALLOW_UNKNOWN_EMAIL_VERIFICATION: ENC[AES256_GCM,data:+c8+9uw=,iv:m2aVcxoE0hdVcfkWEXGH0emQrzmy0+krsQDhS7XdCjo=,tag:NTr2PYu9tLuIZZBJsXaLtg==,type:str]
    SSO_AUTHORITY: ENC[AES256_GCM,data:i+H5DwVp9lz9DEi6BRANjCHRu4/WY3veIaqMow9enTEneAK4Rp/2ZAgFCor8qjPad33/UYD0WfT9fzqGYqkMDdoUL4e5ndSzEmcP,iv:r9lQKpxm6ozkoiOSMFx1YTDhj7DXumGtE+tW9OKShQw=,tag:LdoFxokpKA7s0sMZGLP0Og==,type:str]
    SSO_SCOPES: ENC[AES256_GCM,data:FaarslW55qLvrCK7h/ytGzEEPM2Z9+/xsD+wzvLPAY/Mjww7Zu4M,iv:mIa45Vn/p1ADkod1WcYEe4BhCeh6sYnBho/drVz7OEs=,tag:NbHfKoIDqiGLwbsVMl8jHw==,type:str]
    SSO_CLIENT_ID: ENC[AES256_GCM,data:vKe6pDZ9bAmYNDWEWWDYmB7oBb7xuGSFA4Mblcphf+ZMTZsU,iv:FgKm2PjkGhKQnp6QN3txFN51UFQmLzr9NPQxD6wWf+Q=,tag:Eca67N7aHiXSEBKTSFjn+A==,type:str]
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:DQ4OSi424uBiQBkOmgV6DQowLVd4aYc+/9gTgVjkvUc8ZtvOpgDwbw==,iv:6FEAXlATedMXPSwK8MWDEQQ6+YMuEWA47Vst78zDu5U=,tag:lE+byINGPxaBR9bE8nsUXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12zt98j083qhangw8wg3zhy5zccp6qpw0e677m5jncgdmp94a84rqzvedat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUDdWelhHOU1UK0tLZDM4
            UStMaFRtRThkN3ZjUW5YY1RnaGdLekR4TEUwCjgxUEh4US9YR3FWbGJlQ0dvV05v
            LzVxVE9UNXk3ZnlsQVo5Z3M3eXlWZjgKLS0tIE8rMis1Sm5KUnNkdS8vQVloTE43
            NVI3YlNTZkNEUFdMakJqYlVuSzFTYzAKAcnEJkEXx55pYRC7eHVuL5FkDigbuaq9
            Hlosh0DwESdOp2Lb2tTzKv7blCTUErsNJ1Fp9692tgb7uZkddNEOFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T03:05:47Z"
    mac: ENC[AES256_GCM,data:IHeyc7qfx+69/YcG1adx9s+hyaTqA54XBBTbwnrtier8Z3Ym/LOfXhsXOhzow+ORX2dp/Uc72i60ejSAJiS+BWGkeXBg/1hvyZqlt7uJq9uWpNHgocUG0hO36NBet5mYtA10AyiafiRCkB3gRBCxnFWXVmNwLZd4I1LsCDUa52A=,iv:jdb0r/fP8pkvgHOV+xbycr6X6iVOWTSsKlMg1+qJYAs=,tag:sEKD5Kl425b/7ikU0P2+aw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
