apiVersion: v1
kind: Secret
metadata:
    name: wotlk-accountmgr-invite
    namespace: wotlk
type: Opaque
stringData:
    INVITE_CODE: ENC[AES256_GCM,data:uJvEo/fhnpO8FB1aQkkhcTdfpieyGA==,iv:3ydqQXWda9IDDouFyqB5T+Ura1E8rB27KEn8l/IMGTA=,tag:v4uzEMpZ1bg5bygzTCKyig==,type:str]
sops:
    age:
        - recipient: age12zt98j083qhangw8wg3zhy5zccp6qpw0e677m5jncgdmp94a84rqzvedat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUGtHUHcvSFl6U0VNamNa
            OENNVHBFN0ZKTGdOektOSWR0SlJyTE1TTWdjCnhkWU8rTWhnL2xpN2l2ZHhDT2xF
            cUQwNWlQUitaeURDdDhxWlRZK0FTREUKLS0tIEtHMG5rNzEyQ2xQdmNCck1TOUJ1
            VWMrR2NOMm5ieW5BNzZ0M3ZoRWl5RTAKj3lFQtcjpq11OoBteYkV8iFbcCHKDN6J
            NzqIH+CFyQ8p2EKLvGtbjUwgRaMpVfCUelhA5P76IKE+vzEf9zZAhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T04:50:28Z"
    mac: ENC[AES256_GCM,data:SiZ3CBlOBmcL8Q9D5BDjukynKGOyrwpLNYvXxKYlcqhJpXswYjTRKneyDin5qBAwGNet8ky4yRxruAc6Gs7xdreoTqM9Vp5e3aEcj1NodYgnCXJT6lRoFpyw8aBb9SSTAKsaTdlJPT4YcHq2R38P9fARH/H7X1M12kA11rvb/54=,iv:h0ls+huZJD9t0S5YzMsmLa65R64YKBSvD1bBD3CHIIA=,tag:MAfKHKp4BTLPfSyLrrG56Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
