apiVersion: v1
kind: Secret
metadata:
    name: wotlk-accountmgr-invite
    namespace: wotlk
type: Opaque
stringData:
    INVITE_CODE: ENC[AES256_GCM,data:LBMIIh2LXO0I,iv:lUa7ynoFHS1APY2EmxjCOtUz9cGz303dI1d2p/x8mzU=,tag:NoYIPWX/Z3LlxkmScm4l2Q==,type:str]
sops:
    age:
        - recipient: age12zt98j083qhangw8wg3zhy5zccp6qpw0e677m5jncgdmp94a84rqzvedat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUGtHUHcvSFl6U0VNamNa
            OENNVHBFN0ZKTGdOektOSWR0SlJyTE1TTWdjCnhkWU8rTWhnL2xpN2l2ZHhDT2xF
            cUQwNWlQUitaeURDdDhxWlRZK0FTREUKLS0tIEtHMG5rNzEyQ2xQdmNCck1TOUJ1
            VWMrR2NOMm5ieW5BNzZ0M3ZoRWl5RTAKj3lFQtcjpq11OoBteYkV8iFbcCHKDN6J
            NzqIH+CFyQ8p2EKLvGtbjUwgRaMpVfCUelhA5P76IKE+vzEf9zZAhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T04:31:58Z"
    mac: ENC[AES256_GCM,data:cyLUmCmrv7j8xhlq9JwALUm5Csl/EXNVRuZLbqNZWF2pQWNoW2fz2Gr7i7O5/c4PkgzQE5FUFmUw1RrK+vpEt8N7h7ZOTGxYtvtRp4Kxe3MKGGOYODsNZNjSdEyQ5l74ZgkOrE+XAs96fLdL61pniyngeOUxuI5F3GVEqUIigqc=,iv:YdsBqQRjNnnjf/IAT9voGeeyyxtt1JJ5EpM7Upxqbko=,tag:ivNaZk4/7wE43WqLb21l9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
