apiVersion: v1
kind: Secret
metadata:
    name: wotlk-soap-auth
    namespace: wotlk
type: Opaque
stringData:
    SOAP_USERNAME: ENC[AES256_GCM,data:oZUxcYSJDGgx,iv:emTUdZ0SRM2QlkPVFTxsXs1QQSMipkqFz2zjW1Xafvw=,tag:y1+fr4MstK282Rg2wyqknQ==,type:str]
    SOAP_PASSWORD: ENC[AES256_GCM,data:5myt5tIaxdvb,iv:/+Wb6JQR2ZadjqhJ2PtFlACnN5lPwFhwH7lrLtiy4ro=,tag:G+JANSui6hm9KqGRX0XkeQ==,type:str]
sops:
    age:
        - recipient: age12zt98j083qhangw8wg3zhy5zccp6qpw0e677m5jncgdmp94a84rqzvedat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTalVXQk1IWHJWVTVyaUp5
            Qi9lVHNRLzBDbW11bjFkcEhTaDQxdzZEZ1VJCnRtN2FPdE9FNGNrbXEyWFVFUTM3
            R3poU0txRW5nTnc3QlZxUDJ1S1p6a1kKLS0tIDJDaEs2SWZ2dkY3b2o1TUVuTm1W
            dUZkalp4U3RXUjczS2F3dlhGQzFkcncKBJjcuxNHB7ngOJeONU1BzlmJMsxH+vri
            TzEAr66Sqh+V45Vb/UoDsziTtfjbjpMfNVw3gj39QFSNJD8a7UiI5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T04:31:58Z"
    mac: ENC[AES256_GCM,data:RgQGXH7vIAQkTFA00Ev6aIrJe3kO5PPRzcny5821FR5pIjL9rfZAQ1HiQnTC2Q+tOH/Xe+m44RA+UyQ7Tv0ro6MppBW+satmLE8ySQQ7k4/ySG2gT5H+zNIkqGLEJz8MiokJRoprjX5zesSkhlbumgNyPCKS8S0P7vWILGmEETM=,iv:1S1Gm6kLMtP3LfrRMXwZfiQdZas4QEcor+bmvWj71Qs=,tag:kYJaIkgbEXSIFBdN2wKmTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
