apiVersion: v1
data:
    SOAP_PASSWORD: ENC[AES256_GCM,data:9Pzs7sCLtegjepWyn2maGFVBr8TE/KlNJbaJ0tIDShqwBuiTj3j1sg==,iv:4JcJIyWeSUPs9UAAQNHKAVkDM6eyN1sb6KTQgTooUZE=,tag:swDCh6WEzaJGZjubbwYV8Q==,type:str]
    SOAP_USERNAME: ENC[AES256_GCM,data:6vGr8eOdU0pGLQoE,iv:m+6RnmjIlwW22YJoD2OOB0bFppM4rHNkkNJsyuWrJcc=,tag:oaAV5CUf60K39inxciksUA==,type:str]
kind: Secret
metadata:
    name: wotlk-soap-auth
    namespace: wotlk
type: Opaque
sops:
    age:
        - recipient: age12zt98j083qhangw8wg3zhy5zccp6qpw0e677m5jncgdmp94a84rqzvedat
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRVJTWk8rVThvcGoxTG5N
            bDBpb0RzQzc2aHlPR1Q4UUp1MGRvd0FXMUN3CjRPdEZKRkVqYzlDb1FrL01XbkxY
            T0YrMXdKTGRWMUpGZ2dUMnJPVisyakUKLS0tIHJubjR0YnNJdjBDWE5ydFpTVnly
            eDFNeXRHUFNxUS90SHpFOWxMbTNGM2cKn8Ukp5iV9LLHQeXLIDVyhc3C/fWazX/E
            mULESdWTM7vIT0AULnSXkUSWLVQAVydsM6kYPsceIpHcPVrrrTRgpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-01T07:01:21Z"
    mac: ENC[AES256_GCM,data:tQaw+vTY3LBqzVx4SQ9mCw6MJOozMCzSS2AZcFydXtYvv7G74B1o7xTtg0Qsdcw+GdsjGZkDZBdB78G+Gt9uho4+nRSXo4c5jQkkmMX85znyv59dzysL5jSwfPRXNWtGpk01Bdu9ZQ6hIAdQJDF7C7gj3ABpAMqT2T3R2YR1R+Q=,iv:+GROnEdxI3xm2jUgEHoet/NA3RkC5ubS1rzv/W0a99U=,tag:xPKFELCaWvRiCiWuY7ymeQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
